name: Sync Garmin Global to Garmin CN

on:
  workflow_dispatch:
  schedule:
    #  每6小时检查一次
    - cron: "0 */4 * * *"

env:
  # please change to your own config.
  GARMIN_SRC_USER: ${{ secrets.GARMIN_SRC_USER }}
  GARMIN_SRC_PASSWORD: ${{ secrets.GARMIN_SRC_PASSWORD }}
  GARMIN_SRC_IS_CN: ${{ secrets.GARMIN_SRC_IS_CN }}
  GARMIN_SRC_TOKEN_STORE: ${{ secrets.GARMIN_SRC_TOKEN_STORE }}
  GARMIN_DST_USER: ${{ secrets.GARMIN_DST_USER }}
  GARMIN_DST_PASSWORD: ${{ secrets.GARMIN_DST_PASSWORD }}
  GARMIN_DST_IS_CN: ${{ secrets.GARMIN_DST_IS_CN }}
  GARMIN_DST_TOKEN_STORE: ${{ secrets.GARMIN_DST_TOKEN_STORE }}
  GARMIN_SYNC_NUM: ${{ secrets.GARMIN_SYNC_NUM }}
  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sync Garmin Global to Garmin CN
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Global to CN
        run: |
          python garmin_src.py
