name: Sync Garmin Global to Garmin CN

on:
  workflow_dispatch:
  schedule:
    #  每6小时检查一次
    - cron: "0 */4 * * *"

env:
  # please change to your own config.
  GARMIN_GLOBAL_USER: ${{ secrets.GARMIN_GLOBAL_USER }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
  GARMIN_CN_USER: ${{ secrets.GARMIN_CN_USER }}
  GARMIN_CN_PASSWORD: ${{ secrets.GARMIN_CN_PASSWORD }}
  GARMIN_SYNC_NUM: ${{ secrets.GARMIN_SYNC_NUM }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sync Garmin Global to Garmin CN
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Global to CN
        run: |
          python global_to_cn.py
